# Generated by Django 6.0.4 on 2026-06-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='report_file',
            field=models.FileField(blank=True, upload_to='reports/'),
        ),
    ]
