[project]
name = "create-django-project-structure-create-apps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.6",
    "joblib>=1.5.3",
    "numpy>=2.4.6",
    "opencv-python>=4.13.0.92",
    "pandas>=3.0.3",
    "reportlab>=4.5.1",
    "scikit-learn>=1.9.0",
]
